version: "3.9"

services:
  api:
    image: alexeygalt/space_api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    platform: linux/amd64
    ports:
      - 80:80
    volumes:
      - ./docker-config.py:/code/config.py
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    image: alexeygalt/space_api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    platform: linux/amd64
    volumes:
      - ./docker-config.py:/code/config.py
    depends_on:
      pg:
        condition: service_healthy
    command: flask db upgrade
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5